### ISSUE TITLE
Masonry: immutable support

### ISSUE THREAD

**Issue by jackhsu978** [pinterest/gestalt#145]
Currently, Masonry caches measurement by shallow comparing `items`. However, when a component uses Masonry to render items from redux, it is common that the reference of items in redux change, especially when the items are normalized items. When an item's reference is changed, the corresponding component defined in `comp` gets unmounted and remounted, which is undesired. I have seen some hacks in redux reducers that attempt to workaround this problem, but ideally this problem should be handled by Masonry.

One idea is to have Masonry take an optional prop which controls when cache should be invalidated.

**Comment by bishwei** [comment]
@jackhsu978 thanks for filing this issue,  would love to hear more about the specific use case here! 
generally speaking, if a reference to an item changes, its a reasonable default assumption (imo) that its measurement _could_ change since something might have changed that could affect render.

>it is common that the reference of items in redux change, especially when the items are normalized items

Would be curious to hear more about this.  Imo, a normalized data store would help this problem since the reference to the item itself shouldn't be changing unless updates are being made directly to that item.

**Comment by jackhsu978** [comment]
@bishwei Thanks for the quick response. Yes, I think the default behavior (remeasure an item if it could change) is very reasonable. However, we have run into some use cases where we don't want to remeasure.

Here are some use cases:

### Use case 1
Consider a component that renders Pins in Masonry from normalized Pins data in Redux. When it renders Pin Masonry, the normalized Pins object has a small field set (just enough to render the Masonry). When user opens a modal/flyout from the Pin, client would fetch more details from the server and then the reducer would deep [merge](https://lodash.com/docs/4.17.10#merge) fetched data to the existing Pin object in Redux.
```js
function pinFetchReducer(state, action) {
  ...
  return {
    ...state,
    [pin.id]: merge({}, state[pin.id], fetchedPin),
  };
}
```

Since the reducer must be pure, we create a new object in Redux instead of mutating an existing object. The result here is that Masonry tries to remeasure the item, unmounts the Pin component as well as the model/flyout within. While it is true that Pin measurement _could_ change in that case, I think 99% of the time the measurement doesn't change and it will be great if there's a `shouldRemeasure` callback prop.

### Use case 2
Consider a component that renders different types of objects (Pins, Board, ...etc) and we have to create a new object for each Masonry item.
```js
class MyComponent extends React.Component {
  renderItem = ({ data }) => (data.type === 'pin' ? renderPin : renderBoard);

  render() {
    const { boards, pins } = this.props;
    const boardItems = boards.map(board => ({ type: 'board', board }));
    const pinItems = pins.map(pin => ({ type: 'pin', pin }));
    const items = boardItems.concat(pinItems);
    return <Masonry items={items} comp={this.renderItem} ... />;
  }
}
...
export default connect((state, props) => ({
  boards: props.boardIds.map(boardId => state.boards[boardId]),
  pins: props.pinIds.map(pinId => state.pins[pinId]),
})(MyComponent);
```

IIUC, on each re-render, the reference of each object in `items` is changed, causing the masonry to remeasure even if nothing in redux is changed.

**Comment by bishwei** [comment]
@jackhsu978 thanks for the detailed use cases!  So both problems can and should be solved independently of Masonry changes imo.

The main issue in both cases is that we are directly passing `Masonry` an array of pin data, which as you mentioned, has a high rate of change.  We can, instead, change this so that `Masonry` just gets an array of ids and individual components are connected directly to redux. 

```
// Pin
const Pin = ({ pinId, pin }) => <div>...</div>;
export default connect((state, props) => ({
  pin: state.pins[pinId]
});

// Feed
class Feed extends React.Component {
  renderItem = ({ data }) => <Pin pinId={data.id} />;

  render() {
    return <Masonry items={this.props.pinIds} comp={this.renderItem} ... />;
  }
})
```
Yes, you end up with more components connected to the store, but _that's okay_.  This is one of the benefits of having normalized data in the store - we no longer have to construct all our data before passing it into a component.  The problem of doing a `.map` inside mapStateToProps is that, you're _always_ generating a new array regardless of what may or may not have changed.  This would invalidate shallow comparisons for any React components, not just Masonry.  

Lmk if this still doesn't solve your issue, happy to chat more in person.  We're following this pattern on mobile web and its worked pretty well for us.

**Comment by jackhsu978** [comment]
@bishwei Thanks for the detailed answer. I think this will work for us!
