### ISSUE TITLE
Dark mode is incorrect when SSR a page with getStaticProps()

### ISSUE THREAD

**Issue by christianvuerings** [pinterest/gestalt#1844]
**Platform**: desktop & mobile web

**Steps to reproduce:**

1. Enable dark mode
2. Re-render a page which has `getStaticProps` - this is what we use for `react-docgen`

**Expected Result**: Page renders with dark mode enabled
**Actual Result**: Page render with light mode

**Root cause analysis**
Bug was introduced in https://github.com/pinterest/gestalt/pull/1789 /cc @manvoid. You can try it out by setting dark mode and refreshing to https://deploy-preview-1789--gestalt.netlify.app/buttongroup

Locally everything works as expected since Next.js doesn't optimize pages in development (localhost) as it does in production. The issue is that as soon as a page is SSG enabled, Next.js renders the page statically and no longer executes the cookie specific code.

![Screen Shot 2022-01-05 at 9 26 10 PM](https://user-images.githubusercontent.com/127199/148335835-7d30f069-155e-46b7-b745-5e952126fff2.png)

**Potential solution**

* Use `getServerSideProps` instead of `getStaticProps` - does need some extra changes since we only publish `docs/.next`: https://github.com/pinterest/gestalt/blob/991acf413f25ab3b3b06ac73644f514290e1bc82/netlify.toml#L2

**Repro locally**

Repro locally by running the Next.js production build and starting the Next.js server:
```
cd ~/code/gestalt/docs
npm run build
npm start
```

**Comment by dangerismycat** [comment]
This is fixed from #1845, yes?

**Comment by christianvuerings** [comment]
> This is fixed from #1845, yes?

No, that only fixes the `What's New` page. We still have see the issue on any other page which uses `getStaticProps` (all the ones with generated prop tables).

The reason I fixed `What's new` is because it's the first page that folks see.

**Comment by dangerismycat** [comment]
Sounds good. Wasn't there another PR that replaced all the getStaticProps with getServerSideProps? If not, I'm assuming that's our next step?

**Comment by christianvuerings** [comment]
> Sounds good. Wasn't there another PR that replaced all the getStaticProps with getServerSideProps? If not, I'm assuming that's our next step?

@dangerismycat #1845 does fix the issue for the What's new page by changing `getStaticProps` to `getServerSideProps`. It's easy for that page since we don't need to read any data from the filesystem.

However, I think it's be a bit more complex for pages which use generated props, mostly because we only publish `docs/.next` and in this case we need access to `packages/gestalt/src`:
https://github.com/pinterest/gestalt/blob/9dc3ccd0aaf4eccc647e465e073583e58b683f0f/netlify.toml#L2 
https://github.com/pinterest/gestalt/blob/9f71e62c71123eda5ca2e86937f5a3e31080840d/docs/components/docgen.js#L37

I didn't fix the issue myself since it would be a good intro bug to learn more about Next.js and our Netlify deployment.

**Comment by manvoid** [comment]
I started to work on this, I have seen this (let me know what you think):
- Right now we SSG the docs pages, we use information in the src/ files to generate the pages (we use the description and table props)
- This makes this pages static and ignores the cookies code

The proposed solution will be:
- Change all this pages to use getServerSideProps to make them dynamic generated so the cookie code is considered in every request

But we have some situation with this solution:
- The pages will be generated per request so this will decrease the performance of the site
- Since we use the data in the src/ files we will need to deploy this also so the server can generate the pages
- This will be a somewhat big change since it will touch a lot of files

I have some questions:
- Are we ok with this decrease in performance?
- Is the approach I'm suggesting correct?
- Is there a way to have a SSG page but modify some part of it before sending that to the browser?

**Comment by dangerismycat** [comment]
fixed by #1910
