### ISSUE TITLE
SelectList is not visible in Chrome in DarkMode

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#2107]
Steps to reproduct:

1. open chrome in linux
2. open SlectList: https://gestalt.netlify.app/selectlist
3. change to darkMode.

The list under select list is light gray with white background.

Solution: check if its darkmode and render backgroundColor of ```<select> ```as black.

**Comment by ayeshakmaz** [comment]
Hi @zifahm, thanks for bringing this up! All of our "popover" type components (modal, sheet, popover, etc.) have not yet been optimized for dark mode, so we'll be making those updates in the near future. Since this is more of an enhancement to our components, I'm going to close this as a bug, but I'll post back here when we do make that update. Thanks again!
