### ISSUE TITLE
React 18 causing Sheet to flash

### ISSUE THREAD

**Issue by zifahm** [pinterest/gestalt#2156]
React 18 flashes sheets

Go to this example in Sheet
https://gestalt.netlify.app/sheet#Preventing-close-on-outside-click

Click on View Sheet 
Then close the Sheet.

Now you can see after closing the sheet a flash of old Sheet, after the sheet gets closed.

This is mostly because of react 18 I presume.

**Comment by christianvuerings** [comment]
@zifahm you are correct, the bug is caused by React 18 - PR #2104

Before React 18 we don't see the flash:
https://deploy-preview-2103--gestalt.netlify.app/sheet#Preventing-close-on-outside-click
After React 18 we do see the flash:
https://deploy-preview-2104--gestalt.netlify.app/sheet#Preventing-close-on-outside-click

@ayeshakmaz @AlbertCarreras @dangerismycat have we looked into this bug?

**Comment by zifahm** [comment]
Yup I'm still using 17, still havnt migrated.

**Comment by ayeshakmaz** [comment]
@christianvuerings Yes, there's an active bug in our JIRA dashboard for this.
