### ISSUE TITLE
Masonry: Instrument performance timing

### ISSUE THREAD

**Issue by bishwei** [pinterest/gestalt#23]
We can leverage the User Timing API to instrument performance marks in Masonry.  This will provide insight and information into how long we're spending on the internals of Masonry.  

Instrumentations that come to mind:
- [ ] Measurement
- [ ] Layout
- [ ] onScroll
- [ ] resize/reflow
- [ ] cwrp - we currently loop over all the items and see if we need to reflow

**Comment by chrislloyd** [comment]
I've been thinking more about this - I think we should still leave the actual measuring up to client code otherwise we might introduce perf. entry table overflows. However, we should probably take this task to make sure that there are enough hooks for clients to measure this.

I think Measurement & `cwrp` are covered by React's perf timings. Layout could be handled with a perf. wrapped layout function. `onScroll` and resize/reflow feel like concerns for ScrollUtils v2. Thoughts?

**Comment by bishwei** [comment]
Let's chat about this more - I think both are useful (exposing lifecycle hooks for Masonry, where it makes sense, and having built in perf-timings that users can opt into).  I think the key here is opt-in.  By default, we wouldn't perform any perf timings, unless a user opted in (via query param, or some other method).

Quick and dirty example, but I think there is value in something like this where we can overlay Masonry's timings w/ the default react timings
![image](https://user-images.githubusercontent.com/6487551/36991685-4ebecebc-205d-11e8-92b7-e9e506b96dfc.png)
(btw i think these timings are wrong, so don't read into them)

**Comment by christianvuerings** [comment]
Closing out outdated issues, please re-open if this is still an issue
