### ISSUE TITLE
Custom font for Text and Heading.

### ISSUE THREAD

**Issue by khapnm15dh110042** [pinterest/gestalt#441]
Hi everyone, 

I have a trouble when try to change the font of both Text and Heading. Event though I set the font-family is my local font not the system font in index.css, Text and Heading still get the system font-family. 
_The a tag works fine with my new font_

```
body {
  margin: 0;
  padding: 0;
  background-color: #f6f9fc;
  font-family: 'HellshockTeddyBear', sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, 'Courier New', monospace;
}

@font-face {
  font-family: 'HellshockTeddyBear';
  src: local('HellshockTeddyBear'), url(./fonts/HellshockTeddyBear.ttf) format('truetype');
}
```
![screen shot 2018-12-19 at 11 04 28 am](https://user-images.githubusercontent.com/43127547/50198374-f5bb5100-037d-11e9-988e-c58f7029b319.png)

That being said, I inspect this Foxiny element and found that it used the font-family of system, not my local font selected. And I dont know where it comes from. Please give me any suggestion to deal with that. 

Thank you.

**Comment by chrislloyd** [comment]
Hi @khapnm15dh110042 - Gestalt doesn't support overriding the font-styles for text because a lot of the design & spacing has been done considering system fonts. However, if you do want to override them, you should set the font on the `._1` class like this:

```
._1 {
  font-family: 'HellshockTeddyBear', sans-serif;
}
```

However, because this is a hack that we don't really support it will definitely breaking every time you update Gestalt. Be careful.
