### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `verified`.

### ISSUE THREAD

**Issue by AScriver** [pinterest/gestalt#468]
I am getting errors using the Avatar component. Setting the attribute to a boolean true results in:
`Warning: Received 'true' for a non-boolean attribute 'verified'.`

The error also suggests to pass a string instead, where I am met with the error: 
`Warning: Failed prop type: Invalid prop 'verified' of type 'string' supplied to 'Avatar', expected 'boolean'.`

**Comment by pfarejowicz** [comment]
Sounds like you are passing `"true"` instead of `true`. I cant find anything wrong with the component itself https://pinterest.github.io/gestalt/#/Avatar and the react proptyping on the recent release seems to have no issues marking it an optional boolean https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/Avatar.js#L78

Do you have any more info on your error @AScriver ?
