### ISSUE TITLE
Documentation for responsive properties

### ISSUE THREAD

**Issue by durchanek** [pinterest/gestalt#568]
I may be wrong but it looks like there is no documentation on responsive variants of properties, like what are the actual breakpoints or what is the desired behaviour. This makes it very hard to see if I am doing something wrong or there is a bug in the component. E.g. I would expect that setting `smDisplay="none"` hides the component on small screens but in fact, it outputs:
```
@media (min-width: 576px)
._As {
    display: none;
}
```
This feels counter-intuitive because it forces `display="none" smDisplay="block"` but it may be by design. Having a clear documentation would totally help here.

**Comment by christianvuerings** [comment]
@durchanek that's indeed by design - everything we do on gestalt is mobile first so `display="none" smDisplay="block"` is correct.

You can find the list of breakpoints at https://github.com/pinterest/gestalt/blob/master/packages/gestalt/src/breakpoints.json

Feel free to open a PR to add this information to our docs
